repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-ast

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.12
    hooks:
    -   id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--select=I,E,F,UP", "--no-cache"]
    -   id: ruff-format
        args: ["--no-cache"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            "pydantic>=2.11.2",
            "types-requests",
        ]
        exclude: ^(tests/|examples/)
